services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: expense-tracker-backend
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: "server=expense-tracker-db;port=3306;database=expense_tracker_db;user=root;password=root1234"
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge
