version: '3.8'

services:
  expense-tracker-db:
    image: mysql:8
    container_name: expense-tracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: expense_tracker_db
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-proot1234',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - expense-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: expense-tracker-backend
    ports:
      - '8080:8080'
    environment:
      DB_CONNECTION_STRING: 'server=expense-tracker-db;port=3306;database=expense_tracker_db;user=root;password=root1234'
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__Key: 'THIS_IS_A_VERY_LONG_RANDOM_SECRET_KEY_FOR_JWT_SIGNING_1234567890'
    depends_on:
      expense-tracker-db:
        condition: service_healthy
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge
