version: '3.8'

services:
  expense-tracker-db:
    image: mysql:8
    container_name: expense-tracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: expense_tracker_db
    ports:
      - '3307:3306'
    networks:
      - expense-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: expense-tracker-backend
    ports:
      - '8080:8080'
    environment:
      DB_CONNECTION_STRING: 'server=expense-tracker-db;port=3306;database=expense_tracker_db;user=root;password=root1234'
      ASPNETCORE_URLS: 'http://+:8080'
    depends_on:
      - expense-tracker-db
    networks:
      - expense-network
    entrypoint:
      [
        '/wait-for-it.sh',
        'expense-tracker-db:3306',
        '--',
        'dotnet',
        'backend.dll',
      ]

networks:
  expense-network:
    driver: bridge
